import type { NextPage } from 'next'
import Head from 'next/head'

import { useState } from 'react'
import styles from '../styles/Home.module.css'

const myStyles = {
  padding: '10px',
  border: '2px solid #831dbd',
  borderRadius: '4px',
  outline: 'none',
}

const buttonStyles = {
  width: '10rem',
  border: '2px solid #831dbd',
  borderRadius: '4px',
  padding: '10px',
  cursor: 'pointer',
  marginTop: '2rem',
}

const Home: NextPage = () => {
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form className={styles.main}>
        <input
          style={{
            ...myStyles,
          }}
          type="email"
          placeholder="E-mail"
          value={email}
          onChange={(event) => setEmail(event.target.value)}
        />
        <input
          style={{
            ...myStyles,
            marginTop: '10px',
          }}
          placeholder="Password"
          type="password"
          value={password}
          onChange={(event) => setPassword(event.target.value)}
        />

        <button style={{ ...buttonStyles }} type="submit">
          Sign In
        </button>
      </form>
    </div>
  )
}

export default Home
